kind = "web"
previewPath = "/"
title = "SCRB Sanket"
version = "1.0.0"
id = "artifacts/scrb-sanket"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26259

[services.development]
run = "pnpm --filter @workspace/scrb-sanket run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/scrb-sanket", "run", "build" ]
serve = "static"
publicDir = "artifacts/scrb-sanket/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26259"
BASE_PATH = "/"
